# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_picture_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
