# Generated by Django 2.1.dev20180318005124 on 2018-04-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20180404_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
    ]
