# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
