# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_picture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
    ]
