# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180321_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photos.Photographer'),
            preserve_default=False,
        ),
    ]
