# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20180323_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='uploader',
        ),
    ]
