# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_picture_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploader_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
