# Generated by Django 2.1.dev20180318005124 on 2018-04-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20180403_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Tag'),
        ),
    ]
