# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_picture_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
