# Generated by Django 2.0.2 on 2018-04-26 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0015_picture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likeCount',
        ),
        migrations.AddField(
            model_name='like',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Picture'),
        ),
        migrations.AddField(
            model_name='download',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Picture'),
        ),
    ]
