# Generated by Django 2.0.2 on 2018-04-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20180426_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
