# Generated by Django 2.0.2 on 2018-04-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
